# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3de8fe978995ad6121f05a68da442560cf20096a9350bc8dc3264118e9001851b19916ba28d99643d45b8d84ec86ebe0795719adc62045d5bae3982ce57b53a8

test:
  secret_key_base: cc93d9566d5a0fd89e6c0d550c1d7103d91e85f3b23537259c51699293664207a31b3a8504fdaca407e7126dbcfa314333dd772094c9c7e9b49c91f37ba56b25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
